springdoc:
  api-docs:
    path: /api-docs
  show-actuator: false
  show-login-endpoint: true
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    config-url: ${server.path}/api-docs/swagger-config
    url: ${server.path}/api-docs
    disable-swagger-default-url: true
    oauth2-redirect-url: ${server.path}/swagger-ui/oauth2-redirect.html
logging:
  level:
    org.rivero.roommanagement: debug