spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${CLIENT_ID:74de25564b94ce99a0f3}
            client-secret: ${CLIENT_SECRET:1a579834df97028c30f66fa09f4097098a20f95f}