spring:
  main:
    web-application-type: reactive
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: on
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:todo-db
  data:
    web:
      pageable:
        default-page-size: 20
logging:
  level:
    web: debug