spring:
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: on
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:todo-db