server:
  error:
    include-message: always
spring:
  mvc:
    format:
      date-time: iso
  threads:
    virtual:
      enabled: true
springdoc:
  api-docs:
    path: /api-docs
  show-actuator: false
  show-login-endpoint: true
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    config-url: /api-docs/swagger-config
    url: /api-docs
    disable-swagger-default-url: true
    oauth2-redirect-url: /swagger-ui/oauth2-redirect.html
logging:
  level:
    org.rivero.roommanagement: debug
    org.springframework.web: debug
    org.postgresql: trace
    java.sql: trace